os: linux
language: cpp
dist: trusty
sudo: true
compiler: gcc

include:    
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-9
          - g++-9
          - qtmultimedia5-dev
          - qtmobility-dev
          - qtdeclarative5-dev
          - qtbase5-dev



before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
  - sudo apt-get update

install:
  - sudo apt-get install qt58base qt58svg qt58charts-no-lgpl qt58xmlpatterns qt58multimedia libpulse-dev
  - source /opt/qt58/bin/qt58-env.sh


script:
  - /opt/qt58/bin/qmake PREFIX=/usr
  - make
  - cmake -H. -B.build
  - cmake --build .build
  - .build/tests