language: cpp
dist: trusty

include:
  - os: linux
    sudo: true
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-8
          - g++-8
          - qtmultimedia5-dev
          - qtdeclarative5-dev
          - qtbase5-dev


script:
  - /opt/qt58/bin/qmake PREFIX=/usr
  - make